name: Build Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:    
    uses: lumentae/actions/.github/workflows/build-cpp.yml@main
    with:
      vcpkg_packages: glfw3 imgui[glfw-binding,opengl3-binding] cpp-httplib openssl nlohmann-json CURL
      project_name: tt_music_viewer
      system_packages: libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
  release:
    permissions:
        contents: write
    needs: build
    uses: lumentae/actions/.github/workflows/release.yml@main
    with:
      commit-message: ${{ github.event.head_commit.message }}
    
